import { Inter } from 'next/font/google';
import Script from 'next/script';

// adding bootstrap globaly
// import './globals.css';
// import 'bootstrap/dist/css/bootstrap.css';
// import 'rsuite/dist/rsuite.css'
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Apollo Project Next',
  description: 'Generated by Apollo Teams',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" />
    </html>
  );
}
